apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy: { }
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: postgres:13.1
          name: database
          resources: { }
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "myData1"
