apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
data:
  application-prod.properties: |
    logging.file.name=/app/logs/gateway.log
    zuul.routes.book.path=/book/**
    zuul.routes.book.url=http://book.spring-cloud-kube.svc.cluster.local
    zuul.routes.account.path=/account/**
    zuul.routes.account.url=http://account.spring-cloud-kube.svc.cluster.local
    zuul.routes.customer.path=/customer/**
    zuul.routes.customer.url=http://customer.spring-cloud-kube.svc.cluster.local
