--liquibase formatted sql

--changeset Dan Halverson:1-customer
CREATE TABLE CUSTOMER
(
    ID          INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER UNIQUE,
    NAME        VARCHAR(100),
    TYPE        VARCHAR(100)
);
--rollback DELETE TABLE ACCOUNT;

--changeset Dan Halverson:2-customer
INSERT INTO CUSTOMER (ID, CUSTOMER_ID, NAME, TYPE)
VALUES (1, 12345, 'Steve Sanders', 'INDIVIDUAL');
INSERT INTO CUSTOMER (ID, CUSTOMER_ID, NAME, TYPE)
VALUES (2, 12346, 'Monica Lewinsky', 'INDIVIDUAL');
INSERT INTO CUSTOMER (ID, CUSTOMER_ID, NAME, TYPE)
VALUES (3, 12347, 'Bill Clinton', 'INDIVIDUAL');
INSERT INTO CUSTOMER (ID, CUSTOMER_ID, NAME, TYPE)
VALUES (4, 12348, 'Heidi Fleiss', 'INDIVIDUAL');
--rollback DELETE FROM CUSTOMER;
